packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
catalog:
  '@testing-library/jest-dom': ^6.6.4
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^24.2.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@vitejs/plugin-react': ^5.0.0
  eslint: ^9.32.0
  jsdom: ^26.1.0
  react: ^19.1.1
  react-dom: ^19.1.1
  tailwind-merge: ^3.3.1
  turbo: ^2.5.5
  typescript: ^5.9.2
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  zod: ^4.0.15
